### PR TITLE
Tablet  and Desktop views

### PR DESCRIPTION
**Pull request by musyelevateher**
Added  Tablet and Desktop view to a mobile-first website to make it fully responsive.

### CODE REVIEW

**Review by Xfarouq — CHANGES_REQUESTED** [review]
Hi @musyelevateher 

Good job so far!
You still need to work on some issues to get your project approved, but you are almost there!

<div style="text-align:center;">
    Remote Collaboration
</div>

### To Highlight 💯
- **Clean code** 👍
- **Good use of Gitflow** 👍
- **Implemented some project requirements** 👍

### Required Changes ♻️

- Everything looks good but the only problem is your website is overflowing i.e. (Your website if moving horizontal from left to right which we don't want that), your website should only move vertically i.e. (top to bottom) and the problem causing your website to overflow are your movie video image and your headers images
- for the header images it's best to use Position Relative on your parent container and position absolute for the header images, then you can adjust the images to all be at the center by using left and top variables or tranform
- for the movie image make sure to set the width to 100% of it's section

### Optional Suggestions
Every comment with the `[OPTIONAL]` prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding! 👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.  
Please, remember to tag me in your question so I can receive the notification._

**Review by Xfarouq — CHANGES_REQUESTED** [review]
Hi @musyelevateher 

Good job so far!
You still need to work on some issues to get your project approved, but you are almost there!

<div style="text-align:center;">
    Remote Collaboration
</div>

### To Highlight 💯
- **Clean code** 👍
- **Good use of Gitflow** 👍
- **Implemented some project requirements** 👍

### Required Changes ♻️
- Make your website especially the section which i will attach the image below to be centrallly aligned 
- 
image
- Try adjusting the blue blurry image to avoid making the website to overflow i.e.(Making your website moving horizontally, moving left to right)

### Optional Suggestions
Every comment with the `[OPTIONAL]` prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding! 👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.  
Please, remember to tag me in your question so I can receive the notification._

**Comment by musyelevateher** [comment]
Please I need more explanation

**Comment by Xfarouq** [comment]
Sorry just seeing this, please reach out to me on slack to know where your
having issues.
Thanks

**Review by Xfarouq — APPROVED** [review]
Hi @musyelevateher 

Your project is complete! There is nothing else to say other than... it's time to merge it!!!
Congratulations! 🎉

<div style="text-align:center;">
    Remote Collaboration
</div>

### Highlights
- ✅ **Professional Readme**
- ✅ **Good use of Gitflow**
- ✅ **UI looks like the Figma design**
- ✅ **Good use of HTML semantics**
- ✅ **Professional commit messages**
- ✅ **Professional PR title**
- ✅ **Professional PR description**

### Optional Suggestions
Every comment with the `[OPTIONAL]` prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding! 👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.  
Please, remember to tag me in your question so I can receive the notification._

**Pull request merged**
